"""Lyrixa Code Orchestrator (Phase 0 skeleton)

Responsible for coordinating plan -> generate -> apply_patch -> verify -> commit.
This initial implementation is intentionally minimal and synchronous.

Contracts (stable for internal callers):
    plan(intent: str, scope: list[str] | None) -> PlanResult
    generate(step_index: int, dry_run: bool = True) -> PatchResult
    apply_patch(diff_text: str, dry_run: bool = False) -> PatchResult
    verify(run_spec_tests_gate: bool = True, run_quality_gates: bool = True) -> VerifyResult
    commit(message: str, sign: bool = False) -> CommitResult

Autonomy modes (env or param): assist | co-drive | autopilot
Behavior (Phase 0):
    assist   : never auto-apply patches; only preview
    co-drive : auto-apply patches classified 'low' risk (placeholder heuristic)
    autopilot: apply all patches after verify passes and create git commit

Risk heuristic (placeholder): patch line count <= 50 => low.

Note: Further phases will delegate to specialization agents & analysis modules.
"""

from __future__ import annotations

import os
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from . import audit, ops_engine, safety


# -------- Result dataclasses ---------
@dataclass
class PlanStep:
    description: str
    target_files: list[str] = field(default_factory=list)
    tests_required: bool = True


@dataclass
class PlanResult:
    intent: str
    steps: list[PlanStep]
    created_at: float


@dataclass
class PatchResult:
    applied: bool
    dry_run: bool
    diff: str
    rollback_token: str | None = None
    summary: str | None = None
    diagnostics: list[str] = field(default_factory=list)


@dataclass
class VerifyResult:
    passed: bool
    spec_tests_gate: bool
    quality_gates: bool
    aether_risk: bool
    diagnostics: list[str] = field(default_factory=list)


@dataclass
class CommitResult:
    committed: bool
    sha: str | None
    message: str
    diagnostics: list[str] = field(default_factory=list)


# ------------- Orchestrator ----------------
class CodeOrchestrator:
    def __init__(self, repo_root: str | Path = ".") -> None:
        self.repo_root = Path(repo_root).resolve()
        self._plan: PlanResult | None = None
        self.mode = os.getenv("AETHERRA_MODE", "assist")

    # ---- Public API ----
    def plan(self, intent: str, scope: Optional[List[str]] = None) -> PlanResult:
        # Simple heuristic: every listed scope file becomes one step
        steps: list[PlanStep] = []
        files = scope or []
        if not files:
            # Fallback: user wants to generate tests for next commit (demo)
            files = ["tests/"]
        for f in files:
            steps.append(PlanStep(description=f"Edit or create {f}", target_files=[f]))
        self._plan = PlanResult(intent=intent, steps=steps, created_at=time.time())
        audit.record_event(
            "plan", {"intent": intent, "steps": [s.description for s in steps]}
        )
        return self._plan

    def generate(self, step_index: int, dry_run: bool = True) -> PatchResult:
        if not self._plan:
            raise RuntimeError("No active plan; call plan() first")
        if step_index < 0 or step_index >= len(self._plan.steps):
            raise IndexError("step_index out of range")
        step = self._plan.steps[step_index]
        # Placeholder: generate a comment header if file exists, else create file with TODO
        target = Path(step.target_files[0])
        if target.exists():
            diff = ops_engine.build_comment_insertion_diff(
                target, f"Generated by Lyrixa for intent: {self._plan.intent}"
            )
        else:
            diff = ops_engine.build_new_file_diff(
                target, f"# TODO: implement for intent: {self._plan.intent}\n"
            )
        summary = f"Proposed patch touching {target}"
        audit.record_event("generate", {"step": step_index, "target": str(target)})
        return PatchResult(applied=False, dry_run=dry_run, diff=diff, summary=summary)

    def apply_patch(self, diff_text: str, dry_run: bool = False) -> PatchResult:
        raw = ops_engine.apply_unified_diff(
            diff_text, repo_root=self.repo_root, dry_run=dry_run
        )
        audit.record_event("apply_patch", {"dry_run": dry_run, "applied": raw.applied})
        # Autonomy mode could auto-stage
        if raw.applied and not dry_run and self.mode in {"co-drive", "autopilot"}:
            self._git_add_from_diff(diff_text)
        pr = PatchResult(
            applied=raw.applied,
            dry_run=raw.dry_run,
            diff=raw.diff,
            rollback_token=raw.rollback_token,
            summary=(
                f"Applied patch ({len(raw.diagnostics)} diag)"
                if raw.applied
                else "Dry run"
            ),
            diagnostics=raw.diagnostics,
        )
        return pr

    def verify(
        self,
        run_spec_tests_gate: bool = True,
        run_quality_gates: bool = True,
        strict_aether: bool = True,
    ) -> VerifyResult:
        diagnostics: list[str] = []
        spec_ok = True
        if run_spec_tests_gate:
            spec_ok = self._run_tool(
                ["python", "tools/spec_tests_gate.py"],
                diagnostics,
                label="spec_tests_gate",
            )
        quality_ok = True
        if run_quality_gates:
            quality_ok = self._run_tool(
                ["python", "tools/quality_gates.py"], diagnostics, label="quality_gates"
            )
        aether_ok = safety.run_aether_risk_verifier(
            strict=strict_aether, diagnostics=diagnostics
        )
        passed = spec_ok and quality_ok and aether_ok
        audit.record_event(
            "verify",
            {
                "passed": passed,
                "spec": spec_ok,
                "quality": quality_ok,
                "aether": aether_ok,
            },
        )
        return VerifyResult(
            passed=passed,
            spec_tests_gate=spec_ok,
            quality_gates=quality_ok,
            aether_risk=aether_ok,
            diagnostics=diagnostics,
        )

    def commit(self, message: str, sign: bool = False) -> CommitResult:
        diagnostics: list[str] = []
        sha = None
        code, out = self._run_git(["git", "commit", "-m", message], capture=True)
        diagnostics.append(out)
        committed = code == 0
        if committed:
            sha = self._git_rev_parse()
            audit.record_event("commit", {"message": message, "sha": sha})
        return CommitResult(
            committed=committed, sha=sha, message=message, diagnostics=diagnostics
        )

    # ---- Helpers ----
    def _run_tool(self, cmd: list[str], diagnostics: list[str], label: str) -> bool:
        try:
            p = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
            )
            out, _ = p.communicate()
            diagnostics.append(f"[{label}]\n" + out)
            return p.returncode == 0
        except FileNotFoundError:
            diagnostics.append(f"[{label}] tool missing: {' '.join(cmd)}")
            return False

    def _run_git(self, cmd: list[str], capture: bool = False) -> tuple[int, str]:
        p = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE if capture else None,
            stderr=subprocess.STDOUT if capture else None,
            text=True,
        )
        out = ""
        if capture:
            out, _ = p.communicate()
        else:
            p.wait()
        return p.returncode, out

    def _git_rev_parse(self) -> str | None:
        code, out = self._run_git(["git", "rev-parse", "--short", "HEAD"], capture=True)
        if code == 0:
            return out.strip()
        return None

    def _git_add_from_diff(self, diff_text: str) -> None:
        paths: set[Path] = set()
        for line in diff_text.splitlines():
            if line.startswith("*** Update File:"):
                parts = line.split(":", 1)
                if len(parts) == 2:
                    path = parts[1].strip()
                    paths.add(Path(path))
            if line.startswith("*** Add File:"):
                path = line.split(":", 1)[1].strip()
                paths.add(Path(path))
        if paths:
            self._run_git(["git", "add", *[str(p) for p in paths]])


# End of orchestrator skeleton
