"""Typed contracts for the Aetherra Guardian System."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any


class GuardianStatus(StrEnum):
    """Final Guardian decision status."""

    ALLOW = "allow"
    ALLOW_LIMITED = "allow_limited"
    REQUIRE_APPROVAL = "require_approval"
    DENY = "deny"
    CONTAIN = "contain"


class RiskLevel(StrEnum):
    """Guardian risk classifications."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class GuardianDecisionTier(StrEnum):
    """Operational tier used to choose Guardian performance behavior."""

    CRITICAL = "critical"
    PRIVILEGED = "privileged"
    ROUTINE_GUARDED = "routine_guarded"
    OBSERVATIONAL = "observational"
    TELEMETRY_INTERNAL = "telemetry_internal"


class GuardianMode(StrEnum):
    """Guardian operating modes."""

    OBSERVE = "observe"
    ADVISORY = "advisory"
    ENFORCING = "enforcing"
    STRICT = "strict"
    EMERGENCY = "emergency"


class ApprovalState(StrEnum):
    """Approval lifecycle states."""

    AUTOMATIC = "automatic"
    PENDING_USER = "pending_user"
    APPROVED = "approved"
    DENIED = "denied"
    EXPIRED = "expired"


class ContainmentAction(StrEnum):
    """Containment actions Guardian can request."""

    BLOCK_ACTION = "block_action"
    DISABLE_PLUGIN = "disable_plugin"
    PAUSE_AGENT = "pause_agent"
    REVOKE_CAPABILITY = "revoke_capability"
    OBSERVE_ONLY = "observe_only"
    ISOLATE_SUBSYSTEM = "isolate_subsystem"
    EMERGENCY_STOP = "emergency_stop"
    REQUIRE_MANUAL_RECOVERY = "require_manual_recovery"


@dataclass(frozen=True, slots=True)
class IntentDeclaration:
    """A normalized declaration of a meaningful action before execution."""

    requester: str
    subsystem: str
    action: str
    target: str
    purpose: str
    capabilities: tuple[str, ...] = ()
    expected_outcome: str | None = None
    reversible: bool = False
    rollback_plan: str | None = None
    evidence: tuple[str, ...] = ()
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        required = {
            "requester": self.requester,
            "subsystem": self.subsystem,
            "action": self.action,
            "target": self.target,
            "purpose": self.purpose,
        }
        missing = [name for name, value in required.items() if not str(value or "").strip()]
        if missing:
            raise ValueError(f"intent declaration missing required fields: {', '.join(missing)}")

    def to_audit_dict(self) -> dict[str, Any]:
        """Return a JSON-safe representation for audit records."""

        return asdict(self)


@dataclass(frozen=True, slots=True)
class RiskAssessment:
    """Risk score and factors for an intent."""

    level: RiskLevel
    score: int
    factors: tuple[str, ...] = ()

    @property
    def requires_approval(self) -> bool:
        return self.level in {RiskLevel.HIGH, RiskLevel.CRITICAL}

    @property
    def requires_containment(self) -> bool:
        return self.level == RiskLevel.CRITICAL and any(
            factor in self.factors
            for factor in {
                "security_modification",
                "identity_modification",
                "emergency_mode",
            }
        )


@dataclass(frozen=True, slots=True)
class PolicyResult:
    """Policy or capability check result."""

    allowed: bool
    reason: str
    missing_capabilities: tuple[str, ...] = ()
    details: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class GuardianAuditRecord:
    """Serializable Guardian audit event payload."""

    intent: IntentDeclaration
    risk: RiskAssessment
    decision: GuardianDecision


@dataclass(frozen=True, slots=True)
class ReversibilityResult:
    """Rollback/recovery validation result for a Guardian intent."""

    valid: bool
    required: bool
    reason: str
    rollback_plan: str | None = None
    details: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class ApprovalRequest:
    """Human or elevated approval request generated by Guardian."""

    request_id: str
    intent: IntentDeclaration
    risk: RiskAssessment
    state: ApprovalState = ApprovalState.PENDING_USER
    created_at: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat().replace("+00:00", "Z")
    )
    expires_at: str | None = None
    required_approvers: tuple[str, ...] = ("user",)

    def to_record(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class ApprovalValidationResult:
    """Result of checking whether an approval can authorize an intent."""

    valid: bool
    reason: str
    request_id: str | None = None
    approver: str | None = None
    details: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class GuardianDecision:
    """Final Guardian decision for an intent."""

    status: GuardianStatus
    risk_level: RiskLevel
    reason: str
    constraints: tuple[str, ...] = ()
    required_approvals: tuple[str, ...] = ()
    rollback_required: bool = False
    audit_id: str | None = None
    containment_actions: tuple[ContainmentAction, ...] = ()
    details: dict[str, Any] = field(default_factory=dict)

    @property
    def allowed(self) -> bool:
        return self.status in {GuardianStatus.ALLOW, GuardianStatus.ALLOW_LIMITED}

    def with_audit_id(self, audit_id: str | None) -> GuardianDecision:
        return GuardianDecision(
            status=self.status,
            risk_level=self.risk_level,
            reason=self.reason,
            constraints=self.constraints,
            required_approvals=self.required_approvals,
            rollback_required=self.rollback_required,
            audit_id=audit_id,
            containment_actions=self.containment_actions,
            details=self.details,
        )

    def to_audit_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class CapabilityGrant:
    """A scoped Guardian capability grant."""

    entity: str
    capability: str
    scope: str = "*"
    granted_by: str = "guardian"
    created_at: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat().replace("+00:00", "Z")
    )


@dataclass(frozen=True, slots=True)
class PreauthorizationGrant:
    """A scoped, short-lived Guardian grant for repeated routine actions."""

    grant_id: str
    requester: str
    subsystem: str
    action: str
    target: str
    capabilities: tuple[str, ...] = ()
    intent_fingerprint: str = ""
    decision_tier: GuardianDecisionTier = GuardianDecisionTier.ROUTINE_GUARDED
    guardian_mode: GuardianMode = GuardianMode.ENFORCING
    policy_fingerprint: str = ""
    max_uses: int = 1
    created_at: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat().replace("+00:00", "Z")
    )
    expires_at: str | None = None
    granted_by: str = "guardian"
    audit_required: bool = True
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_record(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True, slots=True)
class PreauthorizationValidationResult:
    """Result of validating a preauthorization grant against an intent."""

    valid: bool
    reason: str
    grant_id: str | None = None
    details: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class ContainmentResult:
    """Recorded containment action result."""

    containment_id: str
    action: ContainmentAction
    intent: IntentDeclaration
    reason: str
    created_at: str = field(
        default_factory=lambda: datetime.now(UTC).isoformat().replace("+00:00", "Z")
    )
    active: bool = True

    def to_record(self) -> dict[str, Any]:
        return asdict(self)
