#!/usr/bin/env python3
"""
Replace verbose auto-generated README files with concise versions.

SPDX-License-Identifier: GPL-3.0-or-later
SPDX-FileCopyrightText: 2025 Aetherra Labs and Contributors
"""

from pathlib import Path


def create_concise_readme(directory: Path, purpose: str = None) -> str:
    """Generate a concise README for a directory."""
    dir_name = directory.name

    # Determine purpose from directory name if not provided
    if not purpose:
        purpose_map = {
            "ai": "AI integration and multi-LLM management",
            "agents": "Agent definitions and orchestration",
            "api": "REST API endpoints and middleware",
            "cli": "Command-line interface tools",
            "config": "Configuration management",
            "core": "Core framework modules",
            "data": "Data storage and management",
            "docs": "Documentation and guides",
            "events": "Event system and handlers",
            "gui": "Graphical user interface components",
            "integration": "External system integrations",
            "memory": "Memory systems and storage",
            "plugins": "Plugin system and implementations",
            "scripts": "Utility scripts and tools",
            "tests": "Test suites and testing utilities",
            "tools": "Development and administration tools",
            "ui": "User interface components",
            "utils": "Utility functions and helpers",
            "web": "Web interface and components",
        }
        purpose = purpose_map.get(
            dir_name, f"{dir_name.replace('_', ' ').title()} components"
        )

    return f"""# {dir_name}

{purpose}

See the parent directory documentation for more information about the Aetherra framework.

<!-- SPDX-License-Identifier: GPL-3.0-or-later -->
<!-- SPDX-FileCopyrightText: 2025 Aetherra Labs and Contributors -->
"""


def is_verbose_autogenerated_readme(content: str) -> bool:
    """Check if a README appears to be verbose auto-generated content."""
    markers = [
        "This README was automatically generated",
        "Directory containing",
        "This directory contains",
        "## Contents",
        "### File Types",
        "organized as follows",
        "## Development Notes",
        "Follow the established naming conventions",
    ]

    # Must have multiple markers to be considered verbose auto-generated
    marker_count = sum(1 for marker in markers if marker in content)
    return marker_count >= 3


def fix_verbose_readmes(root_dir: Path, dry_run: bool = False) -> list[Path]:
    """Find and fix verbose auto-generated README files."""
    fixed_files = []

    for readme_path in root_dir.rglob("README.md"):
        # Skip root README (we handled that manually)
        if readme_path == root_dir / "README.md":
            continue

        # Skip git and node_modules
        if any(
            skip in str(readme_path) for skip in [".git", "node_modules", "__pycache__"]
        ):
            continue

        try:
            content = readme_path.read_text(encoding="utf-8")

            if is_verbose_autogenerated_readme(content):
                directory = readme_path.parent
                new_content = create_concise_readme(directory)

                if dry_run:
                    print(f"Would fix: {readme_path.relative_to(root_dir)}")
                else:
                    readme_path.write_text(new_content, encoding="utf-8")
                    print(f"Fixed: {readme_path.relative_to(root_dir)}")

                fixed_files.append(readme_path)

        except Exception as e:
            print(f"Error processing {readme_path}: {e}")

    return fixed_files


def main():
    """Replace verbose auto-generated READMEs with concise versions."""
    root_dir = Path(__file__).parent.parent
    print(f"Scanning for verbose auto-generated READMEs in: {root_dir}")

    # First, do a dry run to see what would be changed
    print("\nDry run - files that would be fixed:")
    dry_run_files = fix_verbose_readmes(root_dir, dry_run=True)

    if not dry_run_files:
        print("No verbose auto-generated READMEs found.")
        return

    print(f"\nFound {len(dry_run_files)} verbose auto-generated READMEs.")

    # Actually fix them
    print("\nFixing verbose READMEs:")
    fixed_files = fix_verbose_readmes(root_dir, dry_run=False)

    print(f"\nFixed {len(fixed_files)} verbose README files.")


if __name__ == "__main__":
    main()
