# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _is_text_file(path: Path) -> bool:
    # simple heuristic
    return path.suffix.lower() in {
        ".py",
        ".md",
        ".txt",
        ".yaml",
        ".yml",
        ".json",
        ".ini",
        ".toml",
    }


def collect_qfac_files(root: Path) -> dict[str, list[str]]:
    root = root.resolve()
    categories: dict[str, list[str]] = {
        "core_package": [],
        "core_other": [],
        "tools": [],
        "configs": [],
        "tests_package": [],
        "tests_other": [],
        "docs": [],
        "other_refs": [],
    }

    # Pre-computed directories
    core_pkg_dir = root / "Aetherra" / "aetherra_core" / "memory" / "qfac"

    # Walk the tree
    for dirpath, _dirnames, filenames in os.walk(root):
        # skip hidden and build dirs
        if any(p.startswith(".") for p in Path(dirpath).parts):
            continue
        # Normalize
        dpath = Path(dirpath)
        for fn in filenames:
            p = dpath / fn
            rel = str(p.relative_to(root)).replace("\\", "/")
            if not _is_text_file(p):
                continue

            lowered = rel.lower()
            is_qfac_path = "qfac" in lowered

            # Category routing
            if core_pkg_dir in p.parents or p == core_pkg_dir:
                if p.is_file():
                    categories["core_package"].append(rel)
                continue

            if rel.startswith("Aetherra/aetherra_core/memory/") and is_qfac_path:
                categories["core_other"].append(rel)
            elif rel.startswith("Aetherra/tools/") and is_qfac_path:
                categories["tools"].append(rel)
            elif rel.startswith("configs/") and p.name.lower().startswith("qfac"):
                categories["configs"].append(rel)
            elif rel.startswith("tests/qfac/"):
                categories["tests_package"].append(rel)
            elif rel.startswith("tests/") and is_qfac_path:
                categories["tests_other"].append(rel)
            elif rel.startswith("docs/") and (
                "qfac" in p.name.lower() or _file_mentions_qfac(p)
            ):
                categories["docs"].append(rel)
            elif is_qfac_path:
                categories["other_refs"].append(rel)

    # Sort entries for stability
    for k in categories:
        categories[k].sort()
    return categories


def _file_mentions_qfac(path: Path) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False
    return "qfac" in text.lower()


def render_index(categories: dict[str, list[str]]) -> str:
    lines: list[str] = []
    lines.append("# QFAC File Index")
    lines.append("")
    lines.append(
        "This file is generated by tools/generate_qfac_file_index.py. Do not edit manually."
    )
    lines.append("")

    def section(title: str, key: str):
        files = categories.get(key, [])
        lines.append(f"## {title} ({len(files)})")
        lines.append("")
        if not files:
            lines.append("- (none)")
        else:
            for f in files:
                lines.append(f"- `{f}`")
        lines.append("")

    section("Core QFAC package", "core_package")
    section("Core memory: other QFAC modules", "core_other")
    section("Tools", "tools")
    section("Configuration", "configs")
    section("Tests: qfac/", "tests_package")
    section("Tests: other QFAC references", "tests_other")
    section("Documentation", "docs")
    section("Other references", "other_refs")

    # Summary at end
    total = sum(len(v) for v in categories.values())
    lines.append("---")
    lines.append("")
    lines.append(f"Total files: {total}")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate QFAC file index.")
    parser.add_argument(
        "--root", default=str(ROOT), help="Repository root (default: project root)"
    )
    parser.add_argument(
        "--output", default="docs/QFAC_FILE_INDEX.md", help="Output markdown file path"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the existing index matches current state",
    )
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    cats = collect_qfac_files(root)
    content = render_index(cats)

    out_path = (root / args.output).resolve()
    if args.check and out_path.exists():
        current = out_path.read_text(encoding="utf-8", errors="ignore")
        if current == content:
            print("[QFAC] Index is up-to-date.")
            return 0
        print("[QFAC] Index is stale. Regenerate with the generator.")
        return 1

    # Write
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"[QFAC] Wrote index to {out_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
