#!/usr/bin/env python3
"""SPDX & Attribution Consistency Checker

Scans repository for source (Python + Markdown) files and verifies presence of:
  - SPDX-License-Identifier: GPL-3.0-or-later
  - SPDX-FileCopyrightText: 2025 Aetherra Labs and Contributors

Reports:
  * Missing headers
  * Mismatched license identifiers
  * Files skipped (binary or vendor paths)
Exit code: 0 if all pass, 1 if any issues.
"""

from __future__ import annotations

import argparse
import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
LICENSE_ID = "GPL-3.0-or-later"
COPYRIGHT_TEXT = "2025 Aetherra Labs and Contributors"

CODE_EXT = {".py", ".md"}
SKIP_DIRS = {
    ".venv",
    "__pycache__",
    "build",
    "dist",
    ".git",
    "node_modules",
    "site-packages",
    "dist-info",
}
OPTIONAL_SKIP = {
    "tests",
    "frontend",
    "final_organization_backup",
    "focused_cleanup_backup",
    "smart_cleanup_backup",
}
# Some top-level autogenerated/log artifacts
SKIP_PREFIXES = {"aetherra_os.log", "lyrixa_basic.log"}

"""Regex patterns (lenient) capture SPDX values even if inside HTML comments.

We later sanitize trailing comment terminators like '-->' so that files using
the HTML comment footer form pass without being flagged as mismatches.
"""
SPDX_RE = re.compile(r"SPDX-License-Identifier:\s*([A-Za-z0-9_.+\-]+)(?:\s+-->)?")
COPY_RE = re.compile(r"SPDX-FileCopyrightText:\s*([^\n]+)")


def iter_files():
    strict = os.environ.get("AETHERRA_STRICT_SPDX") == "1"
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        if path.name in ("LICENSE",):
            # LICENSE handled separately
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if not strict and any(part in OPTIONAL_SKIP for part in path.parts):
            continue
        if any(path.name.startswith(p) for p in SKIP_PREFIXES):
            continue
        if path.suffix.lower() in CODE_EXT:
            yield path


def _sanitize(value: str) -> str:
    # Remove trailing HTML comment close and surrounding whitespace
    return re.sub(r"\s*-->", "", value).strip()


def check_file(path: pathlib.Path):
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception as e:
        return [f"ERROR: {path}: {e}"]
    issues = []
    # Python: expect SPDX near top (first 20 lines). Markdown: allow anywhere
    if path.suffix.lower() == ".md":
        search_space = text  # allow footer placement
    else:
        search_space = "\n".join(text.splitlines()[:20])

    m = SPDX_RE.search(search_space)
    if not m:
        issues.append("missing SPDX-License-Identifier")
    else:
        license_val = _sanitize(m.group(1))
        if license_val != LICENSE_ID:
            issues.append(f"license mismatch: {license_val}")
    c = COPY_RE.search(search_space)
    if not c:
        issues.append("missing SPDX-FileCopyrightText")
    else:
        copyright_val = _sanitize(c.group(1))
        if copyright_val != COPYRIGHT_TEXT:
            issues.append(f"copyright mismatch: {copyright_val}")
    return issues


def insert_headers(path: pathlib.Path) -> bool:
    """Insert SPDX headers if missing (handles partial cases).

    Python: Inserts missing lines directly beneath optional shebang.
    Markdown: Appends HTML comment lines only for missing fields (footer style).
    Returns True if file modified.
    """
    try:
        original = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False

    if path.suffix == ".md":
        # Detect existing anywhere
        has_license = bool(SPDX_RE.search(original))
        has_copyright = bool(COPY_RE.search(original))
        if has_license and has_copyright:
            return False
        append_lines = []
        if not has_license:
            append_lines.append("<!-- SPDX-License-Identifier: GPL-3.0-or-later -->")
        if not copyright:
            pass
        if not has_copyright:
            append_lines.append(
                "<!-- SPDX-FileCopyrightText: 2025 Aetherra Labs and Contributors -->"
            )
        if append_lines:
            path.write_text(
                original.rstrip() + "\n\n" + "\n".join(append_lines) + "\n",
                encoding="utf-8",
            )
            return True
        return False

    if path.suffix == ".py":
        # Only inspect top portion for existing
        head = "\n".join(original.splitlines()[:25])
        has_license = "SPDX-License-Identifier" in head
        has_copyright = "SPDX-FileCopyrightText" in head
        if has_license and has_copyright:
            return False
        lines = original.splitlines()
        new_lines = []
        idx = 0
        if lines and lines[0].startswith("#!/"):
            new_lines.append(lines[0])
            idx = 1
        if not has_license:
            new_lines.append("# SPDX-License-Identifier: GPL-3.0-or-later")
        if not has_copyright:
            new_lines.append(
                "# SPDX-FileCopyrightText: 2025 Aetherra Labs and Contributors"
            )
        if new_lines and not new_lines[-1].strip():
            # avoid double blank
            pass
        new_lines.append("")
        new_lines.extend(lines[idx:])
        path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
        return True
    return False


def main(argv=None):
    parser = argparse.ArgumentParser(description="Verify SPDX headers")
    parser.add_argument(
        "--write", action="store_true", help="Auto-insert missing headers where safe"
    )
    args = parser.parse_args(argv)

    missing = {}
    fixed = 0
    for f in iter_files():
        issues = check_file(f)
        if issues and args.write:
            if insert_headers(f):
                issues = check_file(f)
                fixed += 1
        if issues:
            missing[str(f.relative_to(ROOT))] = issues
    if missing:
        print("SPDX verification FAILED:\n")
        for k, issues in sorted(missing.items()):
            safe_k = k.encode("ascii", "ignore").decode("ascii")
            print(f"- {safe_k}")
            for i in issues:
                print(f"    * {i}")
        if args.write:
            print(f"\nAuto-fix attempted; headers inserted into {fixed} files.")
        print("\nAdd (example at top of .py file):")
        print(
            "# SPDX-License-Identifier: GPL-3.0-or-later\n# SPDX-FileCopyrightText: 2025 Aetherra Labs and Contributors"
        )
        sys.exit(1)
    print("All scanned files contain proper SPDX headers.")
    if args.write:
        print(f"Auto-fix inserted headers into {fixed} files.")


if __name__ == "__main__":
    main()
